name: buddies_and_sports
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  firebase_auth: '4.3.0'
  firebase_core: '2.8.0'
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  get_it: ^7.2.0
  go_router: ^6.5.5
  otp_timer_button: ^1.1.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter
 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
